### ISSUE TITLE
gdb attach won't work

### ISSUE THREAD

**Issue by Vccxx** [skysider/pwndocker#10]
When I tring to use gdb.attach(io) in py script using pwntools.
 An Error occurred said :
`Waiting for debugger: debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope)`
![image](https://user-images.githubusercontent.com/21141761/95311890-d4b05100-08c0-11eb-9e61-4b4b08d7ec57.png)

Here is my exp code:
~~~python
from pwn import *
context.log_level = "debug"
context.terminal = ["tmux","splitw","-h"]
io = process("./login") 
io.recvuntil("Input the username:")
io.sendline("a"*0x7a)
gdb.attach(io)
io.recvuntil("Input the password:")
io.sendline("b"*0x10)
io.interactive()
~~~

I have searched for this problem and tried method listed as below,All of them didn't work:

1. add `--privilidged` option to the docker start file:
    ~~~sh
     docker run -d \
        --rm \
        -h $1 \
        --name $1 \
        -v $(pwd)/$1:/ctf/work \
        -p 23946:23946 \
        --privileged \
        --cap-add=SYS_PTRACE \
        skysider/pwndocker

     docker exec -it $1 /bin/bash
    ~~~
2. add `--security-opt seccomp=unconfined` option to the docker start file:
    ~~~sh
      docker run -d \
        --rm \
        -h $1 \
        --name $1 \
        -v $(pwd)/$1:/ctf/work \
        -p 23946:23946 \
        --privileged \
        --cap-add=SYS_PTRACE \
        --security-opt seccomp=unconfined \
        skysider/pwndocker

       docker exec -it $1 /bin/bash
    ~~~
3. add `--security-opt apparmor=unconfined` option to the docker start file:
    ~~~sh
      docker run -d \
        --rm \
        -h $1 \
        --name $1 \
        -v $(pwd)/$1:/ctf/work \
        -p 23946:23946 \
        --privileged \
        --cap-add=SYS_PTRACE \
        --security-opt apparmor=unconfined \
        --security-opt seccomp=unconfined \
        skysider/pwndocker

       docker exec -it $1 /bin/bash
    ~~~
4. run `echo 0 > /proc/sys/kernel/yama/ptrace_scope`

Basic System Information:
Machine that running docker: Ubuntu 20.04 running on Virtual Box

**Comment by Vccxx** [comment]
It seems that it's not the problem of gdb , because I can attach the process outside the python script (using the gdb shell command).

It looks like the problem lies in the pwntools python lib, since I have found some issue about this problem in their repo:
[https://github.com/Gallopsled/pwntools/issues/973](pwntools issue)

I have checked two  elf files , one is 32 Bits ELF and another is 64 Bits ELF, and both of them can be debugged in the gdb in bash. The same error occur in both of them. So I believe it's not the problem of ELF file to be debug.

I still can't fix the gdb.attach problem in the py script. Hope an elegant way can be found to solve it .

**Comment by skysider** [comment]
@Vccxx , Maybe you should try the lastest skysider/pwndocker with `docker pull skysider/pwndocker`. 
 I compile a test program in my docker environment and it suceeds:
test.c
```
#include <stdio.h>
int main()
{
    puts("test");
   getchar();
   puts("done");
}
```
and I run `docker run -it --privileged skysider/pwndocker/ /bin/bash`, and it works.
![test](https://user-images.githubusercontent.com/5803275/95578533-9a80b400-0a66-11eb-91b4-eb6a7c341c71.jpg)

**Comment by Vccxx** [comment]
I have test your test program on my docker and it doesn't work , here is how I did:
Firstly I start the docker with command : 
`sudo docker run -it --privileged skysider/pwndocker /bin/bash`
Secondly I compile the test.c file with `gcc test.c -o test`, which contains the following code:
~~~c
#include <stdio.h>
int main()
{
    puts("test");
   getchar();
   puts("done");
}
~~~
 Thirdly I write the exp.py:

~~~python
from pwn import *
context.log_level = "debug"
context.terminal = ["tmux","splitw","-h"]
io = process("./test")
io.send("1")
gdb.attach(io)
io.interactive()
~~~

and then I run the exp.py , get stuck here:
~~~sh
root@d3f8a524e41e:/ctf/work# python3 test_exp.py 
[+] Starting local process './test' argv=[b'./test'] : pid 38
[DEBUG] Sent 0x1 bytes:
    49 * 0x1
[*] running in new terminal: /usr/bin/gdb -q  "./test" 38
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '/usr/bin/gdb -q  "./test" 38']
[-] Waiting for debugger: debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope)
~~~

and after about 1 minute, the program just exit without debugger attached:

~~~sh
root@d3f8a524e41e:/ctf/work# python3 test_exp.py 
[+] Starting local process './test' argv=[b'./test'] : pid 38
[DEBUG] Sent 0x1 bytes:
    49 * 0x1
[*] running in new terminal: /usr/bin/gdb -q  "./test" 38
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '/usr/bin/gdb -q  "./test" 38']
[-] Waiting for debugger: debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope)
[*] Switching to interactive mode
[*] Process './test' stopped with exit code 0 (pid 38)
[DEBUG] Received 0xa bytes:
    b'test\n'
    b'done\n'
test
done
[*] Got EOF while reading in interactive
$ 
[DEBUG] Sent 0x1 bytes:
    10 * 0x1
[*] Got EOF while sending in interactive
~~~

Would you please show me your exp.py? I think there maybe some coding problem.

**Comment by Vccxx** [comment]
OK, It turns out that I didn't run exp.py in a tmux terminal but in a bash terminal......

the debugger works fine in tmux terminal.

Thank you for your time.
