### ISSUE TITLE
不知道root密码，如何使用ida附加调试

### ISSUE THREAD

**Issue by jsk2017** [skysider/pwndocker#11]
每次都是新docker，每次打开Pwndocker都需要设置一遍root的密码才行，能否在dockerfile中直接设置一个默认密码呢？

**Comment by skysider** [comment]
ida附加调试不需要root密码，只需要把调试端口映射出来就可以了

**Comment by jsk2017** [comment]
感谢师傅！
另外，还有一个问题，这两天我在使用pwndocker调试HITCON-Training/LAB/lab2时发现，此题在pwndocker下无法利用成功，而在ubuntu18.04的虚拟机中可以成功利用，感觉像是在pwndocker中bss段中的代码无法执行。
![1](https://cdn.jsdelivr.net/gh/jsk2017/imags-bed@master/20210522/xxx.209tu56iobz4.png)

![xxx](https://cdn.jsdelivr.net/gh/jsk2017/imags-bed@master/20210522/xxx.28m56nqzlyas.png)

另外HITCON-Training/LAB/lab3的题目也是类似的问题，同样在pwndocker中无法成功，而在ubuntu18.04的虚拟机中可以成功利用，并且我相信这不是虚拟机的问题，而是docker中可能有某个设置需要开启。
希望师傅解答一下疑惑，感谢。

**Comment by skysider** [comment]
@jsk2017  ，你看下在pwndocker下和虚拟机的内存映射情况吗？即使开了NX，bss段也不一定是可执行的
