### ISSUE TITLE
pwn version is not for tmux

### ISSUE THREAD

**Issue by zer0-1s** [skysider/pwndocker#13]
```
git clone --depth 1 https://github.com.cnpmjs.org/Gallopsled/pwntools.git
pip install --upgrade --editable ./pwntools
```

**Comment by itewqq** [comment]
Maybe it's better to checkout to `beta` branch? The default branch is `dev` and had caused some problems to me lol
```
git clone https://github.com.cnpmjs.org/Gallopsled/pwntools.git
cd ./pwntools
git checkout beta
cd ..
pip install --upgrade --editable ./pwntools
pip list | grep pwntools
# pwntools 4.8.0b0
```

**Comment by qrzbing** [comment]
Hi, I think we can do a easy check and upgarde pwntools. I wrote a [personal Dockerfile](https://github.com/qrzbing/pwn-docker/blob/master/Dockerfile) based on this repo, and update pwntools by instruction below:

``` dockerfile
RUN pwntools_update=$(pip show pwntools | grep Version | awk -F, '{print substr($1, 10, 3)}' | awk -v num1=$1 -v num2=4.8 'BEGIN{print(num1<num2)?"1":"0"}') && \
    if [ $pwntools_update -eq 1 ]; then python3 -m pip install -U --no-cache-dir pwntools==4.8.0b0; fi && \
    unset pwntools_update && \
```

and I hope a easier way to update it, or this repo author can update his script.

**Comment by skysider** [comment]
@qrzbing , I plan to set PWNTOOLS_VERSION environment in build action as pwntools is not stable
