### ISSUE TITLE
Error: Authentication required to pull the image

### ISSUE THREAD

**Issue by AlessandroZanatta** [skysider/pwndocker#14]
Hi,

first of all, thanks for this image, it has been of great help when pwning!
I think there is an issue with the Dockerfile, as pulling the image from scratch yields to an error:

```
> docker pull skysider/pwndocker:latest
latest: Pulling from skysider/pwndocker
345e3491a907: Pull complete 
57671312ef6f: Pull complete 
5e9250ddb7d0: Pull complete 
469c73a16ba5: Pull complete 
6d234dc15284: Pull complete 
42cbb779a68f: Pull complete 
726d55798abf: Downloading [=========================>                         ]  156.5MB/306MB
511af35a6a8b: Download complete 
18c5e01ba678: Download complete 
5f90fb92201d: Download complete 
e376bbea8312: Download complete 
14641206fa09: Download complete 
1ea7e5742d7c: Download complete 
a2aa00890aee: Download complete 
d726458fad58: Downloading [=====>                                             ]  33.76MB/294.8MB
8f7ea1bd4f01: Download complete 
0e3bb34b7406: Download complete 
6ef28762945f: Downloading 
bf5fd95ca7c6: Waiting 
dfc489ce0e2d: Waiting 
0bf33740dafa: Waiting 
b98b027f6ebd: Waiting 
8acef8e579a8: Waiting 
2ee39d26bcf6: Waiting 
12441af2add7: Waiting 
c70656af2b50: Waiting 
2d0d71ee97a3: Waiting 
50ea63e52fc0: Waiting 
e9a6fb786549: Waiting 
3a54190c7994: Waiting 
d96ea314b9a1: Waiting 
docker: unauthorized: authentication required.   <------------ Error here!
```

It looks like it happens when docker tries to download the image with (partial?) hash `6ef28762945f`.

## How to reproduce
Steps:

1. Remove the image locally
2. Pull the image again

**Comment by skysider** [comment]
@AlessandroZanatta I try to reproduce in pure arch linux, and it just works well. Maybe there is something wrong with your proxy?

**Comment by AlessandroZanatta** [comment]
> @AlessandroZanatta I try to reproduce in pure arch linux, and it just works well. Maybe there is something wrong with your proxy?

I tried again today, it worked with no issues. Haven't changed anything relevant on my side. As long as it is fixed, that's okay I guess! Sorry for the useless report.
