### ISSUE TITLE
Feature request: include glibc 2.34~2.36 in the docker image

### ISSUE THREAD

**Issue by wongsingfo** [skysider/pwndocker#15]
This repo is really useful! Thanks for sharing. 

The glibc included in the docker image are kind of outdated. Ubuntu 22.04 now uses glibc 2.35 but the image only support glibc 2.31. Can we add the latest libc (2.34~2.36) to the docker image?

**Comment by skysider** [comment]
> This repo is really useful! Thanks for sharing.
> 
> The glibc included in the docker image are kind of outdated. Ubuntu 22.04 now uses glibc 2.35 but the image only support glibc 2.31. Can we add the latest libc (2.34~2.36) to the docker image?

Sure，I'll add the latest libc version to the docker image this month
