### ISSUE TITLE
I can't change the interpreter

### ISSUE THREAD

**Issue by Th3R4nd0m** [skysider/pwndocker#4]
I run
> patchelf --set-interpreter /glibc/2.23/64/lib/ld-2.23.so ./binary

and I run ldd on the binary
/glibc/2.23/64/lib/ld-2.23.so => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f0118a0a000)

It stills points to the default libc. If I try to set LD_PRELOAD to the 2.23 libc, it crashes.

**Comment by skysider** [comment]
@Th3R4nd0m, the ld path you changed is longer than its default interpreter path in the binary, you should move ld-2.23.so to /tmp/ld.so, and set the binary interpreter path to /tmp/ld.so

**Comment by Th3R4nd0m** [comment]
yep, tried that
![image](https://user-images.githubusercontent.com/43180911/77845073-8ead5e80-71b4-11ea-8739-df07d111882c.png)

**Comment by skysider** [comment]
@Th3R4nd0m ，ldd itself use default system ld path to analyze binary, you can just gdb the patched binary to see the memory map, the loaded ld binary should be modified path.
