### ISSUE TITLE
是否可以提供各版本glibc源码调试支持

### ISSUE THREAD

**Issue by fubuki8087** [skysider/pwndocker#5]
目前的pwndocker提供了glibc流行版本的编译文件，但是gdb调试进libc时没有对应的源码信息，是否可以为每个版本提供源码调试支持？

**Comment by skysider** [comment]
@fubuki8087，每个版本的glibc的源码可以从gnu的官网下载，在用gdb调试时指定源码路径即可

**Comment by fubuki8087** [comment]
我在使用pwndocker时，使用gdb.attach()附加调试，会显示
```
pwnlib.exception.PwnlibException: Could not find a terminal binary to use. Set context.terminal to your terminal.
```
我看网上其他的说法是要设置`context.terminal`为指定的终端，并给出参数，但我不知道pwndocker要怎么写
